export type CaseStudy = {
  id: number;
  slug: string;
  title: string;
  service: string;
  location: string;
  industry: string;
  subjectMatterExpert: string;
  serviceProvider: string;
  summary: string;
  sections: Array<{
    heading: string;
    paragraphs?: string[];
    bullets?: string[];
  }>;
  appendix?: string[];
};

export const caseStudies: CaseStudy[] = [
  {
    id: 1,
    slug: 'corporate-espionage-mumbai-financial-hub',
    title: 'Neutralizing Corporate Espionage in a Mumbai Financial Hub',
    service: 'TSCM & Bug Sweeping Services',
    location: 'Bandra Kurla Complex (BKC), Mumbai',
    industry: 'Investment Banking / FinTech',
    subjectMatterExpert: 'Wahid Shaikh (TSCM Expert & Risk Advisor)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A prominent investment banking firm in BKC traced sensitive acquisition leaks to a physically planted listening device inside its executive conference environment.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'In early 2026, a prominent investment banking firm headquartered in Mumbai’s BKC district suspected a significant data leak. Despite robust cybersecurity protocols, sensitive boardroom discussions regarding a multi-billion dollar acquisition were appearing in competitor reports.',
          'The problem was not digital; it was physical. The client required immediate espionage detection services to identify potential illicit monitoring devices within their executive suite.',
        ],
      },
      {
        heading: 'The Objective',
        bullets: [
          'Audio transmitters: real-time listening devices.',
          'Hidden cameras: pin-hole lenses monitoring confidential documents.',
          'Audio recorders: passive devices used for later retrieval of data.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Under the leadership of Wahid Shaikh, a specialized team from Indiebim Technology Solutions was deployed. The operation was scheduled over a weekend to ensure zero operational downtime and total discretion.',
        ],
        bullets: [
          'Non-Linear Junction Detector (NLJD): to find electronic components even if the bug was powered off.',
          'Spectrum Analyzer: to monitor the RF environment for unauthorized transmissions.',
          'Thermal Imaging: to detect heat signatures generated by concealed power sources.',
          'Near-Field Receiver: for rapid detection of local transmitters.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The sweep covered the boardroom, CEO’s office, and the private dining area. During the counter-surveillance activity, the team identified a sophisticated, GSM-based audio transmitter concealed within a standard-looking power strip in the main conference room.',
          'The device allowed an external party to listen to high-level negotiations through a mobile network from virtually any location.',
        ],
      },
      {
        heading: 'The Solution & Outcome',
        paragraphs: [
          'Indiebim Technology Solutions removed the threat and conducted a forensic analysis of the device to determine its origin. Wahid Shaikh provided a post-operation risk advisory report outlining new physical security protocols.',
        ],
        bullets: [
          'Immediate threat removal: the eavesdropping device was neutralized.',
          'Corporate hardening: a quarterly TSCM schedule was implemented to prevent future breaches.',
          'Peace of mind: the leadership team regained the confidence to discuss sensitive M&A activities.',
        ],
      },
    ],
  },
  {
    id: 2,
    slug: 'protecting-intellectual-property-bengaluru',
    title: 'Protecting Intellectual Property in Bengaluru’s Silicon Valley',
    service: 'TSCM, Debugging, and IP Protection Services',
    location: 'Electronic City, Phase 1, Bengaluru, Karnataka',
    industry: 'Semiconductor Research & Development (R&D)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A semiconductor R&D firm in Bengaluru uncovered a hardwired LTE eavesdropping device above its conference table after prototype designs began surfacing with a competitor.',
    sections: [
      {
        heading: 'Introduction',
        paragraphs: [
          'In the hyper-competitive world of semiconductor design, a single leaked schematic can result in billions of dollars in lost revenue and years of wasted research. Bengaluru is a prime target for global corporate espionage.',
          'This case study examines a high-stakes operation conducted for a leading R&D firm facing an internal security crisis.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'In mid-April 2026, the executive board of a major tech firm in Electronic City noticed a disturbing trend: a competitor was filing patents for specialized chip architectures that were strikingly similar to their own unreleased prototypes.',
          'Despite air-gapped servers and strict NDAs, the leak appeared to be happening inside the physical war room used by lead engineers.',
        ],
        bullets: [
          'Audio recorder detection: possible passive recorders planted during cleaning shifts.',
          'Audio transmitter detection: real-time eavesdropping via high-frequency bugs.',
          'Hidden camera detection: monitoring of whiteboards and physical blueprints.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'The firm engaged Indiebim Technology Solutions, and Wahid Shaikh personally led the specialized counter-intelligence unit. The team arrived under the guise of network infrastructure auditors to avoid alerting any internal moles.',
          'The operation moved beyond basic RF detection into high-level forensic hardware analysis.',
        ],
        bullets: [
          'RF spectrum analysis using a real-time spectrum analyzer up to 24GHz to separate legitimate wireless traffic from unauthorized burst transmissions.',
          'NLJD scanning to locate dormant store-and-forward devices that remain silent until nighttime transmission windows.',
          'Grid-by-grid physical inspection of HVAC vents, smoke detectors, and power outlets.',
        ],
      },
      {
        heading: 'The Solution',
        paragraphs: [
          'The breakthrough occurred in the executive boardroom’s false ceiling, where the team discovered an LTE-based eavesdropping device integrated into a modified emergency lighting ballast.',
          'The device was hardwired into the building’s power supply and used a 5G SIM card to transmit high-quality audio to an offshore server.',
        ],
      },
      {
        heading: 'Outcome and Risk Advisory',
        bullets: [
          'Hardware hardening: replaced standard electrical fittings with tamper-evident sealed units.',
          'Frequency jamming: installed localized white-noise generators in the war room to neutralize missed or future audio threats.',
          'Policy change: mandated monthly TSCM quick-sweeps and quarterly deep-dives.',
        ],
      },
      {
        heading: 'Conclusion',
        paragraphs: [
          'This case underscores that in 2026, standard security guards and CCTV are insufficient against modern threats. By engaging Indiebim Technology Solutions and leveraging Wahid Shaikh’s investigative experience, the client successfully plugged a multi-million dollar leak and secured its future intellectual property.',
        ],
      },
    ],
    appendix: [
      'OSCOR Blue for high-speed spectrum analysis to find illicit transmitters.',
      'TALAN 3.0 for analyzing digital telephone lines and VoIP systems for wiretaps.',
      'FLIR thermal cameras to find the heat signature of hidden cameras behind walls.',
    ],
  },
  {
    id: 3,
    slug: 'pharmaceutical-counter-espionage-hyderabad',
    title: 'Counter-Espionage for a Pharmaceutical Giant in Hyderabad',
    service: 'TSCM, Bug Sweeping, and Hidden Camera Detection',
    location: 'HITEC City / Genome Valley, Hyderabad, Telangana',
    industry: 'Pharmaceutical & Life Sciences',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A pharmaceutical manufacturer traced a leak of clinical trial details to a decorative desk clock hiding both a recorder and a live Wi-Fi transmitter.',
    sections: [
      {
        heading: 'The Context',
        paragraphs: [
          'Hyderabad’s Genome Valley is the heart of India’s pharmaceutical innovation. When a company is in the final stages of a new drug formulation or patent filing, the information discussed behind closed doors is worth billions.',
          'Industrial espionage in this environment is a persistent corporate threat.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'A major pharmaceutical manufacturer contacted Indiebim after noticing that proprietary clinical trial data was being discussed in trade circles before the official announcement.',
          'The leak was highly specific, involving data points only discussed in the CSO’s private office and the R&D strategy room.',
        ],
        bullets: [
          'Audio recorder detection: high-fidelity digital voice recorders hidden in furniture.',
          'Audio transmitter detection: GSM or Wi-Fi-based bugs relaying real-time strategy.',
          'Threats for corporate assets: vulnerabilities in the physical clean-room environments where research was conducted.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh deployed a multi-disciplinary team to Hyderabad to conduct a full-spectrum TSCM audit. Because pharmaceutical labs contain sensitive electronic equipment, the sweep had to be executed with extreme precision to avoid interference.',
        ],
        bullets: [
          'RF mapping with a spectrum analyzer across the 10 kHz to 24 GHz range to identify burst transmissions.',
          'Physical electronic search with an NLJD to detect powered-off or batteryless electronic circuits.',
          'Optical lens detection using high-intensity laser scanners to find camera lenses smaller than 2mm.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The sweep of the CSO’s office revealed a sophisticated audio transmitter and a micro-SD digital recorder concealed inside a high-end decorative desk clock that had been received as a gift.',
          'The dual-mode device recorded audio locally and transmitted live through a hidden Wi-Fi module when it detected voice activity.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Forensic analysis of the device and its Wi-Fi MAC address to help identify the source of the gift.',
          'Gift screening policy requiring TSCM scans for electronics entering executive offices.',
          'PSIM protocol to monitor new RF signals in real time.',
        ],
      },
      {
        heading: 'Conclusion',
        paragraphs: [
          'This Hyderabad case demonstrates that counter-surveillance services are a specialized science. By combining Indiebim’s technical expertise with Wahid Shaikh’s strategic risk advisory, the pharmaceutical firm secured its patents and maintained its competitive edge.',
        ],
      },
    ],
    appendix: [
      'REI Oscor Blue for detecting sophisticated low-probability-of-intercept signals.',
      'REI Talan to check digital VoIP phone lines in the R&D center for taps.',
      'Magnum NLJD to find electronics hidden behind specialized lab wall panels.',
    ],
  },
  {
    id: 4,
    slug: 'attorney-client-privilege-gurugram',
    title: 'Safeguarding Attorney-Client Privilege in Gurugram',
    service: 'TSCM, Debugging Services, and Audio Recorder Detection',
    location: 'DLF Cyber City, Gurugram (National Capital Region)',
    industry: 'Legal Services / International Law Firm',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A law firm in Cyber City uncovered a Wi-Fi audio transmitter hidden inside a PIR motion sensor directly above its partner seating position.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'In early 2026, a top-tier international law firm in Gurugram noticed confidential strategy details regarding a major arbitration case leaking to opposing counsel.',
          'An internal IT audit found no digital breach, leading investigators to focus on physical eavesdropping within the war room or senior partner cabin.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Modern glass-heavy offices in Gurugram create unique vulnerabilities for counter-surveillance work, including laser microphone risk and open-plan acoustic leakage.',
        ],
        bullets: [
          'Audio recorder detection: digital recorders smaller than a coin that can capture hundreds of hours.',
          'Laser microphone vulnerability: glass partitions exposed to adjacent buildings.',
          'Threats for corporate reputation: malpractice exposure and privilege failure.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Indiebim initiated a midnight deep sweep under Wahid Shaikh’s direct supervision, combining technical sweeps with physical security audits.',
        ],
        bullets: [
          'Near-field RF spectrum analysis for store-and-forward bugs.',
          'Acoustic leakage testing through HVAC ducts and glass windows.',
          'NLJD scans across furniture, chairs, and desks for hidden semiconductor junctions.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team discovered a high-gain audio transmitter integrated into a PIR motion sensor in the main conference room, directly above the partner’s seat.',
          'The device used the building’s Wi-Fi network through a masked SSID to stream encrypted audio in real time.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Installed speech protectors that emit non-filtered ultrasonic noise to disrupt hidden microphones.',
          'Applied anti-laser window film to prevent long-range laser microphone attacks.',
          'Commissioned background checks for third-party vendors and facility-management staff.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The law firm restored client confidence and was able to issue a security integrity certificate supported by military-grade TSCM countermeasures.',
        ],
      },
    ],
    appendix: [
      'REI ANDRE for near-field broadband detection of nearby transmitters.',
      'Wolfhound-PRO to track the cellular signature of the hidden GSM bug.',
      'Laser Mic Defeat System to test and harden the glass facade.',
    ],
  },
  {
    id: 5,
    slug: 'industrial-espionage-pune-automotive-hub',
    title: 'Neutralizing Industrial Espionage in Pune’s Automotive Hub',
    service: 'TSCM, Bug Sweeping Services, and Counter Surveillance',
    location: 'Chakan / Pimpri-Chinchwad, Pune, Maharashtra',
    industry: 'Automotive Manufacturing (EV Sector)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'An EV manufacturer uncovered both an audio recorder in a commemorative trophy and a hidden Wi-Fi camera inside a designer desk lamp.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'In early 2026, a Tier-1 automotive manufacturer specializing in EVs suspected its proprietary battery management system designs were being compromised during a critical prototype phase.',
          'The suspected leak centered on the design studio and the managing director’s strategy cabin.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'In a modern Industry 4.0 facility, massive IoT, robotics, and Wi-Fi noise make bug detection more difficult, allowing illicit hardware to hide within legitimate electromagnetic activity.',
        ],
        bullets: [
          'Audio transmitter detection to protect design discussions.',
          'Hidden camera detection to prevent visual theft of 3D models and prototypes.',
          'Threats for corporate assets including server rooms and design archives.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh orchestrated a sweep during a scheduled maintenance shutdown to preserve secrecy. The team established a baseline of the factory’s RF environment and scanned suspect items with thermal imaging and NLJD tools.',
        ],
        bullets: [
          'High-speed spectrum analysis to isolate unknown RF signals.',
          'FLIR thermal imaging to identify heat signatures inside wall clocks, smoke detectors, and power strips.',
          'NLJD sweeps across the design studio to locate semiconductor junctions inside non-electronic objects.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team discovered two separate devices: a voice-activated audio recorder inside a commemorative trophy in the MD’s cabin, and a 4K Wi-Fi hidden camera disguised within a desk lamp in the design studio.',
          'Both devices were powered by internal wiring, giving them indefinite operational life.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Forensic tracing of the modified lamp to a former employee who had joined a rival firm.',
          'RF shielding of the design studio to create a localized Faraday cage effect.',
          'Monthly counter-surveillance sweeps for executive cabins and R&D zones.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The manufacturer plugged the leak, identified the likely perpetrator, and secured an EV patent filing valued at over Rs. 500 crores.',
        ],
      },
    ],
    appendix: [
      'MESA Mobility Enhanced Spectrum Analyzer for rapid scanning of large industrial spaces.',
      'Non-Linear Junction Detector for finding bugs in noisy electronic environments.',
      'Video Pole Camera for high-altitude HVAC and ceiling inspections.',
    ],
  },
  {
    id: 6,
    slug: 'domestic-sanctuary-lutyens-delhi',
    title: 'Ensuring Domestic Sanctuary in Lutyens’ Delhi',
    service: 'Residential TSCM, Debugging Services, and Hidden Camera Detection',
    location: 'Golf Links / Amrita Shergill Marg, Lutyens’ Delhi',
    industry: 'High-Net-Worth Individuals (HNI) / Ultra-High-Net-Worth (UHNW)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A discreet residential sweep in Lutyens’ Delhi uncovered a smoke-detector camera and a GSM audio transmitter hidden inside a custom silk lampshade.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A prominent HNI family in Lutyens’ Delhi noticed that private discussions involving inheritance and international property divestment were appearing in anonymous extortion threats.',
          'They required a high-discretion bug sweeping operation that would not alert domestic staff or external security personnel.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Large private residences combine antique furniture, HVAC ducting, and smart-home IoT devices, creating a wide physical attack surface for surveillance devices.',
        ],
        bullets: [
          'Hidden camera detection in bedrooms and study areas.',
          'Audio recorder detection in common family areas.',
          'Threats for individuals including stalking and extortion exposure.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh spearheaded the mission while a two-person Indiebim team operated under the guise of smart-home integration consultants.',
        ],
        bullets: [
          'RF spectrum analysis from 0-24 GHz using a WAM-X25 wireless activity monitor.',
          'Optical lens sweeps with QCC ELF binoculars for powered-off and semi-concealed cameras.',
          'Infrastructure audits of outlets, switches, and junction boxes using a video pole camera.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a pinhole camera hidden in a smoke detector in the master study and a GSM-based audio transmitter embedded in a custom silk lampshade in the dining room.',
          'The camera recorded locally and also streamed short encrypted clips over Wi-Fi, while the audio bug supported live call-in listening.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Installed white-noise based audio masking in the study.',
          'Commissioned rigorous background checks on staff and contractors.',
          'Enrolled the residence in a quarterly TSCM maintenance plan.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The family regained total peace of mind after the extortion threat was neutralized and the residence was hardened as a clean zone.',
        ],
      },
    ],
    appendix: [
      'REI magnetometer for locating electronics behind thick masonry walls.',
      'FLIR thermal imaging for power-supply heat signatures in furniture.',
      'Near-field detector for localized transmitters in dense RF environments.',
    ],
  },
  {
    id: 7,
    slug: 'celebrity-privacy-south-mumbai',
    title: 'Celebrity Privacy Protection in South Mumbai',
    service: 'TSCM, Audio Recorder Detection, and Counter Surveillance',
    location: 'Malabar Hill / Worli Sea Face, Mumbai',
    industry: 'Entertainment / High-Net-Worth Individuals (HNI)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A night-time residential sweep for a celebrity client uncovered a recorder in a gifted air purifier and a GSM bug inside a tablet charging adapter.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A leading Bollywood actor and producer noticed that private scripts and production budgets were leaking to paparazzi and rival production houses.',
          'The pattern suggested active listening inside their South Mumbai residence, requiring a highly discreet TSCM operation.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Luxury residences with rotating staff, stylists, and maintenance crews create elevated risks for covert surveillance and blackmail.',
        ],
        bullets: [
          'Audio transmitter detection for contract negotiations.',
          'Hidden camera detection in private living quarters.',
          'Protection of unreleased film scripts and digital assets.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh designed an Elite Shield operation for the 5,000-square-foot property, with the team working at night to avoid attention from building staff and security.',
        ],
        bullets: [
          '24-hour RF baseline using OSCOR Blue for burst transmitters.',
          'Near-field detection across lamps, home-theater systems, and adapters.',
          'NLJD scans across furniture and custom wall paneling.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a high-fidelity digital audio recorder embedded in an air purifier that had been gifted by a supposed fan, and a second GSM bug inside a standard-looking power adapter used in the vanity room.',
          'The adapter bug was hardwired to the home’s electricity, allowing unlimited monitoring.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Routed all electronic gifts through Indiebim for pre-entry TSCM scanning.',
          'Installed speech protectors using ultrasonic jamming in the study area.',
          'Commissioned deep-dive background checks on domestic staff and security personnel.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The client’s privacy and reputation were protected, and the operation remained fully confidential while neutralizing the surveillance threat.',
        ],
      },
    ],
    appendix: [
      'REI ANDRE for rapid nearby transmitter detection.',
      'QCC ELF optical lens finder for scanning concealed bedroom cameras.',
      'Thermal imaging for hidden transmitters behind wooden paneling.',
    ],
  },
  {
    id: 8,
    slug: 'political-headquarters-kolkata',
    title: 'Securing a Political Headquarters in Kolkata',
    service: 'TSCM, Government-Grade Debugging, and Espionage Detection',
    location: 'Alipore / Bhowanipore, Kolkata, West Bengal',
    industry: 'Government / Political Leadership',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A strategy room in Kolkata was compromised by a professionally embedded UHF transmitter hidden inside a vintage wall clock.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'During a politically charged period in early 2026, a major political party in South Kolkata suspected its strategy meetings were being monitored because opponents were predicting internal decisions with remarkable accuracy.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Many high-profile offices in Kolkata operate from heritage buildings with thick walls, high ceilings, and aging electrical systems, providing ideal concealment for hidden surveillance devices.',
        ],
        bullets: [
          'Audio recorder detection in historic furniture and large filing systems.',
          'Audio transmitter detection using GSM and long-range methods.',
          'Threats for government offices and sensitive policy environments.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Under strict intelligence-grade protocols, Indiebim deployed an elite technical team led by Wahid Shaikh.',
        ],
        bullets: [
          'Full-range RF spectrum analysis from 10 kHz to 24 GHz using OSCOR Blue.',
          'Carrier current analysis across electrical wiring for PLC bugs.',
          'Advanced physical searches of ornate ceilings and internal shafts with video pole cameras.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'In the main strategy room, the team discovered a high-end UHF audio transmitter embedded inside a vintage wall clock.',
          'The device drew power from the clock’s battery circuit and transmitted only when human speech levels were detected.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Installed a high-capacity audio jammer to create an ultrasonic sound wall in the war room.',
          'Redesigned visitor access procedures to ensure escort-based movement for maintenance personnel.',
          'Implemented a quarterly TSCM schedule before every major core-committee meeting.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The headquarters regained strategic integrity and resumed planning with confidence after the physical espionage threat was neutralized.',
        ],
      },
    ],
    appendix: [
      'REI TALAN 3.0 for telephone and digital line analysis.',
      'MESA for fast, high-resolution scanning of large headquarters.',
      'NLJD for electronics hidden inside dense wooden furniture.',
    ],
  },
  {
    id: 9,
    slug: 'critical-infrastructure-ahmedabad',
    title: 'Securing Critical Infrastructure in Ahmedabad',
    service: 'TSCM, Espionage Detection, and Bug Detection Services',
    location: 'Sumel-7 / SG Highway, Ahmedabad, Gujarat',
    industry: 'Government / Critical Infrastructure (Energy & Power)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A command-center investigation revealed a hardware keylogger and audio bridge disguised as a standard network cable on a grid-monitoring workstation.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'In early 2026, a government-affiliated body overseeing critical power distribution in Gujarat suspected a targeted espionage attempt involving smart-grid vulnerabilities and upcoming energy tenders.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'The Ahmedabad site faced high EMF interference from nearby power infrastructure and dense cellular traffic, making it harder to separate normal signal activity from malicious devices.',
        ],
        bullets: [
          'Audio transmitter detection for low-frequency bugs.',
          'Hidden camera detection around control room screens.',
          'Cyber-physical threats from illicit hardware on secure network ports.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a multi-layered infrastructure integrity sweep using a credibility-first methodology designed for technically complex, government-sensitive environments.',
        ],
        bullets: [
          'Broadband RF analysis using OSCOR Blue up to 24 GHz.',
          'LAN and VoIP inspection using TALAN 3.0.',
          'NLJD grid scans across partitions and ceiling tiles for passive bugs.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The sweep of the operations manager’s office uncovered a hardware keylogger and audio bridge disguised as a standard internal network cable plugged into a workstation facing the main monitoring screens.',
          'The device captured keystrokes and streamed audio when it detected a specific voice frequency.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Locked all non-essential ports and applied tamper-evident seals to workstations.',
          'Conducted TSCM training on visual bug detection for senior officials.',
          'Redesigned visitor access protocols around critical workstations.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The operation neutralized a major vulnerability and protected sensitive power-grid intelligence from a likely high-level industrial or state-sponsored threat.',
        ],
      },
    ],
    appendix: [
      'REI OSCOR Blue for signal analysis in high-interference zones.',
      'NLJD for hidden silicon junctions in walls and furnishings.',
      'FLIR thermal imaging for modified network hardware heat signatures.',
    ],
  },
  {
    id: 10,
    slug: 'fintech-algorithms-chennai',
    title: 'Protecting Proprietary FinTech Algorithms in Chennai',
    service: 'TSCM, Debugging Services, and Audio Transmitter Detection',
    location: 'Old Mahabalipuram Road (OMR), Chennai, Tamil Nadu',
    industry: 'FinTech / Software Development',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A fast-growing FinTech startup discovered that a legitimate-looking smart thermostat was secretly operating as a voice-triggered Wi-Fi listening bridge.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A high-growth FinTech startup on Chennai’s OMR suspected that proprietary logic for a new high-frequency trading tool was being replicated by a rival firm shortly after internal discussions.',
          'The CEO concluded the leak was happening through the walls of the executive conference room, not the firewall.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Industrial-style office interiors with exposed ceilings, ducts, and glass partitions offer countless hiding spots for covert hardware and IoT-based surveillance.',
        ],
        bullets: [
          'Audio transmitter detection in a high-density wireless environment.',
          'Audio recorder detection in exposed ceiling infrastructure.',
          'Threats for corporate integrity during a critical funding cycle.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a specialized team from Indiebim to conduct a sweep covering both traditional bugs and smart IoT devices.',
        ],
        bullets: [
          'Wireless activity monitoring to inventory authorized MAC addresses and identify ghost devices.',
          'Physical duct inspections using video pole cameras.',
          'NLJD scans across war-room furniture and fittings.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team discovered a MEMS microphone and Wi-Fi bridge hidden inside a legitimate-looking smart thermostat mounted opposite the CEO’s preferred seat.',
          'The device drew power from HVAC control lines and uploaded encrypted files to a cloud server during lunch breaks when office Wi-Fi traffic was highest.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Removed the bug and handed forensic data to the legal team.',
          'Advised on a dedicated physical security VLAN for IoT devices.',
          'Installed ultrasonic audio jammers in the war room.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The startup secured its intellectual property and continued its Series-C process with confidence that physical espionage had been contained.',
        ],
      },
    ],
    appendix: [
      'WAM-X25 for identifying complex Wi-Fi, Bluetooth, and cellular signals.',
      'Video pole camera for high exposed ceilings.',
      'Spectrum analyzer for unauthorized transmissions hidden within normal traffic.',
    ],
  },
  {
    id: 11,
    slug: 'medical-espionage-pune-biotech-corridor',
    title: 'Combating Medical Espionage in Pune’s Biotech Corridor',
    service: 'TSCM, Espionage Detection, and Debugging Services',
    location: 'Hinjewadi / Magarpatta, Pune, Maharashtra',
    industry: 'Healthcare & Biotechnology (Biomedical Research)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A biotech R&D sweep in Pune identified a high-gain 5G audio transmitter hidden inside the battery backup of a safety exit sign.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A regenerative medicine firm in Pune noticed that confidential experimental data was surfacing in papers from a competitor in Europe.',
          'The client suspected their lab progress meetings were being compromised through a physical breach inside the R&D wing.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Biotech facilities introduce a special challenge: TSCM work must protect sterile zones and sensitive scientific equipment while still identifying covert transmitters.',
        ],
        bullets: [
          'Sensitive equipment that cannot be disrupted.',
          'Audio transmitter detection in low-signal clean-room environments.',
          'Threats for corporate assets involving research valued at over Rs. 800 crores.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh authorized a non-intrusive clean-room protocol, with the team entering sterile zones in Level-3 PPE while carrying advanced debugging equipment.',
        ],
        bullets: [
          'Passive RF monitoring from outside the clean room using a MESA spectrum analyzer.',
          'Acoustic leakage analysis of glass partitions.',
          'NLJD scanning of furniture in the R&D strategy cabin.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team discovered a high-gain audio transmitter disguised inside the battery backup of a safety exit sign in a sterile hallway used for informal scientific discussions.',
          'The bug used a 5G data link and burst-mode transmission to avoid real-time detection.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Deep background checks on facility maintenance vendors.',
          'Localized RF jammers in the strategy cabin.',
          'TSCM awareness training for lead scientists to identify anomalous workplace electronics.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The biotech firm protected its patents and stabilized internal confidence around the integrity of its research environment.',
        ],
      },
    ],
  },
  {
    id: 12,
    slug: 'maritime-security-goa',
    title: 'Maritime Security and Counter-Surveillance in Goa',
    service: 'Maritime TSCM, Hidden Camera Detection, and Audio Recorder Detection',
    location: 'Panjim / Vasco da Gama, Goa',
    industry: 'Maritime Logistics & Luxury Yachting (HNI)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A yacht sweep in Goa uncovered a 4K hidden camera inside a smart mirror and a live-stream GSM audio bug behind a saloon vent.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A high-profile industrialist suspected that private merger negotiations conducted aboard a private vessel in Goa were being recorded after a recent maintenance cycle.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'A ship acts as a giant metal enclosure, creating multipath interference and making bug detection especially difficult in luxury maritime interiors.',
        ],
        bullets: [
          'Audio recorder detection inside cabinetry and upholstery.',
          'Hidden camera detection in staterooms and on the bridge.',
          'Threats for individuals including blackmail and privacy compromise.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'The Indiebim team conducted the sweep while the yacht was at anchor to reduce RF noise and enable a cleaner spectrum baseline.',
        ],
        bullets: [
          'Hull-to-bridge RF scans using OSCOR Blue.',
          'Thermal imaging behind leather wall panels.',
          'Physical inspection of satellite phone and internet infrastructure.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a 4K hidden camera embedded in a smart mirror in the master suite and a high-fidelity audio recorder behind a vent in the dining saloon.',
          'The saloon bug used GSM live streaming, while the mirror camera stored footage locally to encrypted media.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Future maintenance now requires TSCM supervision by Indiebim.',
          'On-board server and Wi-Fi sanitization through Orion Intelligence & Strategic Consultants.',
          'Fresh background screening for the entire yacht crew.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The client regained confidence in holding sensitive business conversations aboard the vessel, demonstrating the team’s ability to secure highly specialized maritime environments.',
        ],
      },
    ],
  },
  {
    id: 13,
    slug: 'high-tech-logistics-indore',
    title: 'Protecting High-Tech Logistics in Indore',
    service: 'TSCM, Debugging Services, and Audio Transmitter Detection',
    location: 'Pithampur Industrial Area / Vijay Nagar, Indore, Madhya Pradesh',
    industry: 'Supply Chain & High-Tech Logistics',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A logistics command center in Indore was compromised by a miniature GSM audio bridge soldered into a desktop intercom unit.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A logistics corporation handling high-value electronics and defense components noticed that competitors seemed to know shipment routes, timing, and security protocols in advance.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Large logistics hubs create a wide attack surface, with open dispatch floors, intercoms, handheld radios, and maintenance access all posing surveillance risks.',
        ],
        bullets: [
          'Audio transmitter detection across large dispatch operations.',
          'Threats for corporate assets involving PA systems and intercoms.',
          'Devices hidden inside industrial hardware or even returned shipping materials.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh deployed the Indiebim team during a shift change to access high-traffic zones without disrupting operations.',
        ],
        bullets: [
          'RF spectrum analysis for rogue dispatch-desk emissions.',
          'Carrier current testing on internal power lines.',
          'NLJD inspection of radios, scanners, and communication units.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team uncovered a miniature GSM audio bridge soldered inside a desktop intercom unit at the dispatch desk.',
          'The modified intercom used its own power source and dialed out to a pre-programmed number whenever it detected voice activity.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Applied tamper-evident seals to communication hardware.',
          'Redesigned vendor-vetting for maintenance personnel.',
          'Delivered TSCM training on recognizing visual anomalies in office equipment.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The firm restored strategic security and reassured clients that sensitive logistics information was once again protected.',
        ],
      },
    ],
  },
  {
    id: 14,
    slug: 'real-estate-espionage-jaipur',
    title: 'Real Estate Espionage and Boardroom Security in Jaipur',
    service: 'TSCM, Hidden Camera Detection, and Counter Surveillance',
    location: 'C-Scheme / Mansarovar, Jaipur, Rajasthan',
    industry: 'Real Estate & Infrastructure Development',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A Jaipur boardroom was compromised by a hidden 4K camera disguised as a motion sensor and a recorder concealed behind a wall painting.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A real estate developer in Jaipur noticed that their bids for a major infrastructure project were being undercut by the exact same margin in repeated tender rounds.',
          'The CEO suspected the executive boardroom was no longer private.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Luxury real estate offices often feature carved wood, false ceilings, and heavy drapery that provide ideal concealment for both hidden cameras and audio recorders.',
        ],
        bullets: [
          'Audio transmitter detection during negotiation phases.',
          'Hidden camera detection aimed at blueprint designs and financial projections.',
          'Threats for corporate integrity linked to tender losses.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh supervised an after-hours deep sweep using specialized tools for premium interior environments.',
        ],
        bullets: [
          'Laser-based optical lens finding across wood carvings and decor.',
          'Thermal imaging of walls and ceilings for concealed power supplies.',
          'NLJD scanning inside an antique conference table.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team discovered a 4K hidden camera disguised as a motion sensor and a high-fidelity audio recorder hidden behind a wall painting.',
          'Both devices used Wi-Fi to transmit data to a nearby hotspot parked outside the building.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Installed ultrasonic audio masking devices.',
          'Audited physical access logs and upgraded security guard protocols.',
          'Established a bi-annual TSCM service agreement.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'With the boardroom secured, the developer finalized strategy in confidence and went on to win the subsequent government tender.',
        ],
      },
    ],
  },
  {
    id: 15,
    slug: 'mining-conglomerate-bhubaneswar',
    title: 'Counter-Espionage for a Mining Conglomerate in Bhubaneswar',
    service: 'TSCM, Espionage Detection, and Audio Recorder Detection',
    location: 'Fortune Towers / Nayapalli, Bhubaneswar, Odisha',
    industry: 'Mining & Natural Resources',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'An executive conference room in Bhubaneswar was compromised by a combined recorder and GSM transmitter hidden inside a stone souvenir.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A mining conglomerate discovered that expansion plans for a new iron ore block were known to a rival down to the last decimal point, indicating a systematic leak from the chairman’s executive suite.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Mining corporate environments often mix executive offices with semi-industrial traffic, gifts, equipment, and visitors, all of which increase the risk of covert hardware placement.',
        ],
        bullets: [
          'Audio recorder detection in personalized executive gifts.',
          'Audio transmitter detection in office electronics.',
          'Threats for corporate assets involving exclusive mineral rights.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a zero-baseline sweep in which every electronic and decorative device in the suite was treated as potentially compromised.',
        ],
        bullets: [
          'Spectrum analysis during active boardroom hours.',
          'NLJD scans of the mahogany desk and wall paneling.',
          'Physical inspection of power sockets and network ports.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a digital audio recorder and GSM transmitter hidden in the base of a heavy stone-carved replica of a Konark Sun Temple wheel gifted by an associate.',
          'The device used burst transmission to send compressed audio files twice daily to a remote server.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Mandated TSCM screening for decorative items in executive areas.',
          'Installed signal-dampening window film to reduce long-range RF interception.',
          'Revamped board-level information security policy.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The conglomerate secured two new blocks in the next auction cycle, avoiding what could have been a severe financial and strategic loss.',
        ],
      },
    ],
  },
  {
    id: 16,
    slug: 'hni-privacy-chandigarh',
    title: 'Safeguarding HNI Privacy in Chandigarh',
    service: 'Residential TSCM, Hidden Camera Detection, and Debugging Services',
    location: 'Sector 9 / Sector 10, Chandigarh (City Beautiful)',
    industry: 'High-Net-Worth Individuals (HNI) / Political Families',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A discreet residential audit in Chandigarh uncovered a Wi-Fi enabled audio-video bug professionally integrated into a smart LED light strip in the family lounge.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'In early 2026, a prominent HNI family in Chandigarh found that private family discussions regarding a sensitive legal settlement were being leaked to the local press.',
          'The family feared blackmail, reputational damage, and wider threats to personal safety, prompting a discreet bug sweeping operation.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Modern mansions in Chandigarh are heavily dependent on smart-home devices, turning televisions, AC units, speakers, and lighting systems into possible surveillance vectors.',
        ],
        bullets: [
          'Hidden camera detection for private dressing rooms and personal areas.',
          'Audio transmitter detection in common family living spaces.',
          'Suspected installations during a recent smart-home upgrade.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh personally supervised the audit while the Indiebim team operated anonymously in an unmarked vehicle to preserve the family’s privacy.',
        ],
        bullets: [
          'IoT audit of the home router logs to identify ghost devices.',
          'Optical sweeps using a laser lens finder across mirrors, clocks, and smoke detectors.',
          'Thermal imaging scans of bedroom furniture and dressing areas for active electronic heat signatures.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team identified a major breach in the family lounge: a Wi-Fi enabled audio-video bug professionally integrated into a smart LED light strip beneath the ceiling cove.',
          'The device used the home’s own Wi-Fi network for live streaming and was controlled remotely via a mobile application.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Reconfigured the home network to isolate IoT devices from the primary family network.',
          'Installed audio jammers in the family’s primary meeting room.',
          'Conducted fresh background checks on house help and security staff.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The family was able to resolve the legal matter in private, reinforcing Indiebim’s role as a trusted protection partner for HNI households in North India.',
        ],
      },
    ],
  },
  {
    id: 17,
    slug: 'textile-design-theft-surat',
    title: 'Neutralizing Textile Design Theft in Surat',
    service: 'TSCM, Debugging Services, and Hidden Camera Detection',
    location: 'Ring Road / Diamond Harbour, Surat, Gujarat',
    industry: 'Textile & Fashion (High-End Ethnic Wear)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A textile design studio in Surat was compromised by a Wi-Fi pinhole camera and micro-audio bug hidden inside a dummy smoke detector above the lead designer’s desk.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A leading textile house in Surat noticed that luxury saree and lehenga designs from its upcoming Winter 2026 collection were appearing as cheap knock-offs before the originals even reached showrooms.',
          'The client suspected that the design studio and sampling room were compromised and needed immediate visual and audio bug detection.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Textile studios are high-clutter environments filled with fabrics, mirrors, mannequins, and lighting fixtures that create countless hiding spots and reflective surfaces.',
        ],
        bullets: [
          'Hidden camera detection focused on drafting tables and design monitors.',
          'Audio recorder detection around sourcing and pricing discussions.',
          'Threats for corporate assets through brand devaluation and mass-market piracy.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh deployed the Indiebim team for a specialized visual and RF sweep designed around creative workspaces.',
        ],
        bullets: [
          'Optical reflectivity scans across mannequin details, buttons, and mirrors.',
          'Near-field RF probing of keyboards, mice, and monitors.',
          'Physical reconstruction of false ceilings and light fixtures to inspect top-down surveillance angles.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The investigation revealed a high-resolution Wi-Fi pinhole camera and a micro-audio bug integrated into a dummy smoke detector placed directly above the lead designer’s desk.',
          'The device streamed images of sketches through a neighboring shop’s Wi-Fi network to avoid the client’s internal IT alerts.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Replaced all dummy sensors with verified tamper-evident security hardware.',
          'Created an RF-silent room for sensitive design discussions.',
          'Revamped facility-management vendor controls and audits.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The textile house launched its collection without further leaks and avoided an estimated Rs. 40 crores in lost revenue.',
        ],
      },
    ],
  },
  {
    id: 18,
    slug: 'petrochemical-security-jamnagar',
    title: 'Petrochemical Security and Espionage Detection in Jamnagar',
    service: 'Industrial TSCM, Bug Detection Services, and Risk Advisory',
    location: 'Jamnagar (Reliance/Nayara Region), Gujarat',
    industry: 'Petrochemicals & Energy',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A petrochemical site in Jamnagar uncovered a laser microphone reflector on window glass and a mains-powered GSM bug hidden inside a wall distribution box.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A petrochemical giant in Jamnagar suspected that refined product pricing strategy and export schedules were being leaked to international traders.',
          'The client needed a government-grade espionage detection service to secure high-level executive boardroom discussions.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Refinery environments generate massive radio noise from industrial sensors, walkie-talkies, and SCADA systems, making it difficult to isolate covert transmitters.',
        ],
        bullets: [
          'Audio transmitter detection for long-range LoRa and GSM devices.',
          'Threats for national and corporate energy interests.',
          'Need for TSCM equipment capable of filtering extreme industrial interference.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a 48-hour Energy Shield operation to establish a quiet spectrum and compare day-time versus night-time emissions.',
        ],
        bullets: [
          'High-speed spectrum analysis using OSCOR Blue.',
          'Harmonic analysis for hidden semiconductor signatures in metal-heavy spaces.',
          'Telephone and line analysis using TALAN 3.0 across copper and fiber infrastructure.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a laser microphone reflector disguised as a tiny patch on executive dining hall window glass and a mains-powered GSM bug hidden in a wall power distribution box.',
          'The GSM device stored a full day of audio and transmitted it in a single high-speed burst at 2:00 AM.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Installed window vibration jammers to defeat laser microphone attacks.',
          'Delivered secure encrypted VOIP solutions for board communications.',
          'Implemented 24/7 RF monitoring in the executive wing.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The leak was stopped and the client regained control over sensitive pricing strategy, strengthening Indiebim’s standing in critical infrastructure TSCM.',
        ],
      },
    ],
  },
  {
    id: 19,
    slug: 'banking-espionage-chennai',
    title: 'Banking Espionage and Financial Security in Chennai',
    service: 'TSCM, Debugging Services, and Audio Transmitter Detection',
    location: 'Anna Salai / Teynampet, Chennai, Tamil Nadu',
    industry: 'Banking & Financial Services (Public Sector & Private)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A Chennai bank uncovered a dual-vector breach involving a digital wiretap on the chairman’s phone junction and a GSM bug hidden inside a desk calculator.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A major private sector bank in Chennai found that highly sensitive information regarding NPA recovery strategies and upcoming interest rate revisions was being leaked to media and rival institutions.',
          'Investigators suspected the boardroom of directors and chairman’s communications were being physically monitored.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'The bank’s headquarters blended modern glass offices with older infrastructure, creating blind spots across phone systems, archives, and executive spaces.',
        ],
        bullets: [
          'Audio transmitter detection in complex telephone exchange environments.',
          'Audio recorder detection hidden inside archival and boardroom spaces.',
          'Threats for corporate integrity including regulatory and reputation risk.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a 72-hour deep-dive TSCM audit with emphasis on voice infrastructure, RF anomalies, and executive-room hardware.',
        ],
        bullets: [
          'Telephone line analysis using REI TALAN 3.0.',
          'RF spectrum analysis for sub-carrier signals hidden within legitimate broadcasts.',
          'NLJD scans across the executive table and leather-lined walls.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'Indiebim discovered a digital wiretap in the main junction box serving the chairman’s office and a GSM audio bug hidden inside a standard-looking desktop calculator.',
          'The wiretap stored calls locally, while the calculator bug enabled live room monitoring.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Oversaw migration to end-to-end encrypted voice systems.',
          'Established a monthly TSCM schedule before board meetings.',
          'Audited cleaning and maintenance staff access to executive floors.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The bank completed its recovery strategy without further leaks and protected its reputation for confidentiality and control.',
        ],
      },
    ],
  },
  {
    id: 20,
    slug: 'luxury-hospitality-udaipur',
    title: 'Luxury Hospitality Privacy in Udaipur',
    service: 'Hospitality TSCM, Hidden Camera Detection, and Audio Recorder Detection',
    location: 'Lake Pichola / Fatehsagar, Udaipur, Rajasthan',
    industry: 'Luxury Hospitality & Tourism (VVIP Guests)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A presidential suite sweep in Udaipur uncovered a night-vision 4K hidden camera concealed inside a vintage-style alarm clock.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A world-renowned palace hotel in Udaipur contacted Indiebim after a celebrity guest claimed they were being filmed in their private suite.',
          'For a five-star property hosting VVIP guests and international events, even the rumor of hidden cameras carried severe brand risk.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Palace-style suites contain ornate mirror work, carved wood, chandeliers, and antique decor that provide excellent camouflage for covert surveillance devices.',
        ],
        bullets: [
          'Hidden camera detection in decorative frames, lighting, and furniture.',
          'Audio transmitter detection during private guest negotiations.',
          'A narrow four-hour sweep window between guest checkout and check-in.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh deployed a rapid-response team that treated the suite as a potential crime scene and preserved evidentiary integrity during the sweep.',
        ],
        bullets: [
          'High-intensity optical lens scanning from multiple room angles.',
          'Thermal imaging across smart TVs and electronic hubs.',
          'NLJD inspection of canopy beds and antique wardrobes.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team located a 4K hidden camera with night vision concealed inside a decorative vintage-style alarm clock in the presidential suite.',
          'The device streamed via a 4G SIM card, completely bypassing the hotel Wi-Fi network.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Cataloged all electronic decor items and applied tamper-evident RFID tags.',
          'Trained the hotel security leadership on visual counter-surveillance.',
          'Implemented routine TSCM sweeps ahead of every VVIP arrival.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The hotel preserved guest trust and public confidence, remaining a top choice for high-profile clientele.',
        ],
      },
    ],
  },
  {
    id: 21,
    slug: 'data-center-security-noida',
    title: 'Protecting the Cloud—Data Center TSCM in Noida',
    service: 'TSCM, Debugging Services, and Physical Security Audits',
    location: 'Sector 144 / Sector 62, Noida, Uttar Pradesh',
    industry: 'Data Centers & Cloud Computing',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A Tier-IV data center in Noida discovered a GSM audio bug hidden inside a modified Cat6 Ethernet cable plugged into a maintenance workstation.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A Noida data center provider noticed unusual RF activity coming from a supposedly dark server-rack area and feared that a physical device had been planted to intercept data or monitor administrative discussions.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Data centers are saturated with electromagnetic interference from servers and power systems, making traditional bug detection more difficult.',
        ],
        bullets: [
          'Audio transmitter detection inside extremely noisy RF environments.',
          'Threats for corporate assets through man-in-the-middle style physical hardware.',
          'Devices disguised as standard SFP modules, cables, or power accessories.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a spectrum-isolation protocol using differential analysis between known server emissions and rogue signals.',
        ],
        bullets: [
          'Near-field analysis across the rear of server racks.',
          'Fiber-optic audits for unauthorized splitters at distribution frames.',
          'NLJD scans across raised flooring and cable trays.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team discovered a GSM-based audio bug hidden inside a modified Cat6 Ethernet cable plugged into a secondary workstation in the NOC strategy room.',
          'Powered over Ethernet, the device streamed audio over GSM and completely bypassed the facility’s firewalls.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Required TSCM verification for all new network cables and modules.',
          'Applied RF-shielding paint to NOC walls.',
          'Conducted a background audit of third-party maintenance contractors.',
        ],
      },
    ],
  },
  {
    id: 22,
    slug: 'political-strategy-lucknow',
    title: 'Guarding Political Strategy in Lucknow',
    service: 'TSCM, Counter Surveillance, and Audio Recorder Detection',
    location: 'Hazratganj / Vidhan Sabha Marg, Lucknow, Uttar Pradesh',
    industry: 'Political Intelligence / Government Leadership',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A stealth sweep in Lucknow revealed a passive digital voice recorder sewn into the underside of a premium leather armchair in a political safe house.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A high-ranking political leader in Lucknow suspected that confidential seat-sharing negotiations were being quoted verbatim in rival circles despite taking place in a supposedly secure safe house.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Older buildings with multiple renovation layers create ideal conditions for hidden devices, while narrow operational windows increase the difficulty of secure sweeps.',
        ],
        bullets: [
          'Audio transmitter detection to stop live listening during sensitive strategy sessions.',
          'A two-hour operational window before a major committee meeting.',
          'Strong need for hidden camera and audio recorder detection in legacy interiors.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh deployed a stealth TSCM unit disguised as telecom infrastructure engineers to avoid drawing suspicion from the surrounding security detail.',
        ],
        bullets: [
          'RF spectrum analysis using OSCOR Blue for burst-transmission bugs.',
          'Thermal imaging across drapery and wood wall panels.',
          'Physical debugging of traditional seating and heavy furniture.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'Indiebim identified a high-capacity digital voice recorder with a 60-day battery life sewn into the underside of a premium leather armchair in the main meeting hall.',
          'Because the device was passive and non-transmitting, it was only discovered through physical search and NLJD-assisted inspection.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Installed portable speech protectors to create a local bubble of silence.',
          'Established a pre-visit sweep protocol for the safe house.',
          'Expanded vetting of domestic and hospitality staff supporting the leader.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The political team finalized strategy in secrecy and maintained campaign control, reinforcing trust in Indiebim’s high-discretion leadership protection work.',
        ],
      },
    ],
  },
  {
    id: 23,
    slug: 'coal-mining-tenders-ranchi',
    title: 'Securing Coal Mining Tenders in Ranchi',
    service: 'TSCM, Bug Sweeping Services, and Espionage Detection',
    location: 'Main Road / Ashok Nagar, Ranchi, Jharkhand',
    industry: 'Natural Resources / Mining & Minerals',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A high-security tender room in Ranchi was compromised by a GSM audio bug and recorder hidden inside a ceremonial coal-extraction trophy.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'In early 2026, a major coal mining corporation in Ranchi discovered that its reserve price calculations for a major government auction had leaked.',
          'With a tiny pricing gap capable of changing the outcome of a thousand-crore tender, the client suspected the tender room itself had been physically compromised.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Mining headquarters face constant traffic from engineers, contractors, and technical visitors, making ruggedized equipment and ceremonial objects plausible hiding places for bugs.',
        ],
        bullets: [
          'Audio recorder detection in rooms filled with technical blueprints and surveying equipment.',
          'Threats for corporate assets involving geological data and bidding strategy.',
          'Suspicion that bugs were hidden inside mining-themed office equipment and decor.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a Deep Vein sweep using a zero-emission scan protocol focused on business-hour burst transmissions, concealed electronics, and parasitic power draw.',
        ],
        bullets: [
          'RF mapping with a spectrum analyzer to isolate signals active only during work hours.',
          'NLJD inspection of surveying tools and mine models.',
          'Power-line analysis for devices drawing hidden current from the main server rack.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team uncovered a miniature GSM audio bug and a power-bank integrated recorder hidden inside a decorative gold-plated first coal extraction trophy in the chairman’s strategy room.',
          'The trophy base had been hollowed out to conceal a bug transmitting audio through a 4G SIM card.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Mandated TSCM scanning for ceremonial gifts before executive-floor placement.',
          'Installed ultrasonic white-noise generators in the tender room.',
          'Audited facility maintenance staff and access history.',
        ],
      },
    ],
  },
  {
    id: 24,
    slug: 'tech-espionage-thiruvananthapuram',
    title: 'Tech Espionage in Thiruvananthapuram’s Technopark',
    service: 'TSCM, Debugging Services, and Hidden Camera Detection',
    location: 'Technopark Phase III, Thiruvananthapuram, Kerala',
    industry: 'IT / Space-Tech & Aerospace',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A space-tech firm in Technopark uncovered a cloned ceiling access point that was actually a 4K hidden camera recording encryption-team screens.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A Space-Tech startup in Thiruvananthapuram working on low-earth-orbit satellite communications suspected that proprietary encryption keys were being visually intercepted.',
          'Although the company had strong digital controls, the physical end-point of the screens remained vulnerable.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'The office environment relied on glass-heavy modern interiors, creating risk for high-resolution visual theft and covert audio interception.',
        ],
        bullets: [
          'Hidden camera detection across smoke detectors, access points, and ceiling fixtures.',
          'Audio transmitter detection for launch-window and engineering discussions.',
          'Threats for corporate integrity including loss of defense-grade contracts.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh supervised the Astro-Shield operation, combining optical inspection, spectrum analysis, and infrastructure review across the R&D area.',
        ],
        bullets: [
          'Laser-based lens sweeps of smoke detectors, sprinkler heads, and clocks.',
          'RF spectrum analysis across 5GHz and 6GHz bands used by modern Wi-Fi cameras.',
          'Infrastructure checks of raised flooring and AC ducts for recorders and hidden hardware.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'Indiebim found a 4K Wi-Fi hidden camera with a downward-facing lens disguised as a standard Wi-Fi access point mounted on the ceiling.',
          'The cloned AP visually matched the company’s official hardware while silently recording the encryption team’s monitors.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Applied tamper-evident labels to all network hardware.',
          'Installed RF jammers to block unauthorized transmission from the R&D zone.',
          'Updated the clean-desk and visual exposure policy for the engineering team.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The startup protected its LEO contract pipeline by hardening the physical layer around critical engineering work.',
        ],
      },
    ],
  },
  {
    id: 25,
    slug: 'hni-privacy-coimbatore',
    title: 'HNI Wealth Protection and Privacy in Coimbatore',
    service: 'Residential TSCM, Debugging Services, and Hidden Camera Detection',
    location: 'Race Course / RS Puram, Coimbatore, Tamil Nadu',
    industry: 'High-Net-Worth Individuals (HNI) / Textile Magnates',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A residential office in Coimbatore was compromised by a pinhole camera hidden inside a bronze statue and a GSM audio bug concealed in a power strip.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A prominent textile tycoon in Coimbatore suspected a breach of domestic privacy after sensitive discussions about an overseas acquisition and family trust matters appeared in regional business coverage.',
          'The client required a discreet bug sweeping service that would not alert household staff or private security.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'The residence combined traditional architecture, dense wood interiors, and broad false ceilings, creating ideal hiding places for passive and active surveillance devices.',
        ],
        bullets: [
          'Hidden camera detection in carved wood and decorative interiors.',
          'Audio recorder detection for passive devices that do not emit RF.',
          'Threats for individuals including extortion and itinerary-based targeting.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a stealth residential audit while the family was away, allowing the team full access without raising suspicion.',
        ],
        bullets: [
          'Full-spectrum RF scanning with OSCOR Blue to isolate unknown 2.4GHz signals.',
          'NLJD inspection of antique furniture and wall-mounted art.',
          'Optical sweeps of the master bedroom and home office.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a high-definition pinhole camera hidden inside a traditional bronze statue on the desk and a GSM audio transmitter hidden inside a standard-looking power strip.',
          'The camera recorded to concealed local media, while the audio bug supported live cellular eavesdropping.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Conducted 360-degree background checks on domestic staff.',
          'Installed ultrasonic noise generators in the home office.',
          'Required TSCM scanning for all gifts and new decor items.',
        ],
      },
    ],
  },
  {
    id: 26,
    slug: 'maritime-espionage-visakhapatnam',
    title: 'Countering Maritime Espionage in Visakhapatnam',
    service: 'Maritime TSCM, Debugging Services, and Espionage Detection',
    location: 'RK Beach / Vizag Port, Visakhapatnam, Andhra Pradesh',
    industry: 'Maritime Logistics & Defense-Adjacent Infrastructure',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A maritime logistics operator in Vizag discovered a modified network router acting as a wireless bridge for stolen port communications.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A private maritime logistics firm in Visakhapatnam found that ship-to-shore communication logs, docking schedules, and cargo manifests were being intercepted.',
          'The client needed a high-authority espionage detection operation across port-side executive offices and the main coordination center.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Vizag port is saturated with radar, marine radio, and satellite activity, making low-power surveillance devices difficult to isolate.',
        ],
        bullets: [
          'Audio transmitter detection within heavy marine VHF traffic.',
          'Threats for corporate assets including sensitive cargo exposure and sanctions risk.',
          'Potential concealment inside ruggedized marine radio or monitoring hardware.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh supervised the Maritime Shield operation using differential signal analysis and hardware-centric inspection of port infrastructure.',
        ],
        bullets: [
          'Real-time spectrum analysis to separate authorized marine signals from unauthorized exfiltration.',
          'Physical line inspection of cable terminations and communications infrastructure.',
          'NLJD scanning of operations-room hardware and safety equipment.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team uncovered a modified network router containing an illicit wireless bridge inside the server room overlooking the port.',
          'The device intercepted unencrypted traffic and relayed it to a nearby fishing vessel equipped with a high-gain antenna.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Replaced network equipment with verified clean hardware and tamper-evident seals.',
          'Installed a 24/7 RF monitoring station for anomalous signal alerts.',
          'Revamped communications protocols and operational security procedures.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The firm secured its logistics chain and restored confidence around the movement of sensitive civilian and defense-adjacent cargo.',
        ],
      },
    ],
  },
  {
    id: 27,
    slug: 'corporate-espionage-nagpur-logistics-hub',
    title: 'Neutralizing Corporate Espionage in Nagpur’s Logistics Hub',
    service: 'TSCM, Debugging Services, and Audio Recorder Detection',
    location: 'MIHAN / Wardha Road, Nagpur, Maharashtra',
    industry: 'Logistics & Multi-Modal Infrastructure',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A logistics office in Nagpur uncovered an audio transmitter and Wi-Fi bridge hidden inside a serviced multifunction printer.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A major infrastructure firm managing an SEZ in Nagpur noticed that expansion bids and land acquisition pricing were being mirrored by a rival consortium.',
          'The client suspected that executive meeting rooms were no longer secure and needed immediate counter-surveillance support.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Large open-plan SEZ offices with glass partitions create ideal acoustic and physical conditions for covert monitoring.',
        ],
        bullets: [
          'Audio transmitter detection in high-ceiling industrial office environments.',
          'Audio recorder detection in shared workspaces.',
          'Threats for corporate assets including loss of high-value government tenders.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh coordinated a weekend logistics shield audit to preserve discretion while scanning both RF and power-line pathways.',
        ],
        bullets: [
          'RF spectrum analysis to identify hopping-frequency signals.',
          'Carrier current analysis of the building power network.',
          'NLJD-assisted inspection of desks, electronics, and office infrastructure.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a high-gain audio transmitter and Wi-Fi bridge hidden inside a high-end office multifunction printer in the finance director’s office.',
          'The hardware drew power from the printer’s internal board and sent audio clips over the office Wi-Fi every hour.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Applied tamper-evident labels to office electronics.',
          'Installed ultrasonic noise generators in the boardroom.',
          'Revamped vendor-access protocols for the MIHAN facility.',
        ],
      },
    ],
  },
  {
    id: 28,
    slug: 'entertainment-ip-protection-hyderabad-film-city',
    title: 'Entertainment IP Protection in Hyderabad’s Film City',
    service: 'TSCM, Hidden Camera Detection, and Counter Surveillance',
    location: 'Ramoji Film City / Banjara Hills, Hyderabad, Telangana',
    industry: 'Entertainment & Media (Film Production)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A production office in Hyderabad discovered a 4K camera and audio bug built into a standard-looking USB wall charger in the lead actor’s vanity area.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A production house filming a major pan-India blockbuster found that private script discussions were being leaked to fan pages before the official campaign rollout.',
          'The client faced both celebrity privacy risks and intellectual-property exposure.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Film environments are high-turnover spaces with constant movement by cast, vendors, and day-wage crews, making hidden camera control especially difficult.',
        ],
        bullets: [
          'Hidden camera detection in makeup rooms and edit suites.',
          'Audio transmitter detection during script readings.',
          'Daily operational sweeps required before cast arrival.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh assigned a dedicated TSCM unit throughout pre-production to maintain sanitized rehearsal and edit environments.',
        ],
        bullets: [
          'Laser-based lens scans of mirrors, fixtures, and props.',
          'Real-time RF monitoring during readings and rehearsals.',
          'Physical inspection of temporary partitions and furniture for recorders.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a 4K hidden camera and audio bug integrated into a standard-looking USB wall charger left in the lead actor’s vanity area.',
          'The charger functioned normally while streaming video over a 4G connection.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Created phone-free sanitized zones with recurring four-hour sweeps.',
          'Audited security staff and support personnel backgrounds.',
          'Secured the edit-suite local network with additional advisory controls.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The film preserved its creative reveal and avoided substantial marketing damage before trailer launch.',
        ],
      },
    ],
  },
  {
    id: 29,
    slug: 'gemological-secrets-jaipur',
    title: 'Safeguarding Gemological Secrets in Jaipur',
    service: 'TSCM, Debugging Services, and Hidden Camera Detection',
    location: 'Johari Bazaar / Sitapura Industrial Area, Jaipur, Rajasthan',
    industry: 'Gems & Jewelry (Luxury Export)',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and Chief Investigative Officer)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A jewelry design vault in Jaipur was compromised by a Wi-Fi pinhole camera and micro-audio bug concealed inside an LED spotlight.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A major jewelry exporter in Jaipur found that exclusive Maharaja Collection designs were being duplicated overseas before the official launch.',
          'The client suspected industrial espionage within a secure design vault and executive suite environment.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Jewelry labs and showrooms combine mirrors, glass, reflective gemstones, and focused lighting that make visual bug detection unusually complex.',
        ],
        bullets: [
          'Hidden camera detection across heavily reflective design spaces.',
          'Audio transmitter detection in dense traditional office furniture.',
          'Threats for corporate assets through loss of exclusivity and brand value.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh led a jeweler’s-eye sweep using micron-level physical and electronic inspection across the design vault.',
        ],
        bullets: [
          'Optical reflectivity scanning across display cases and mirrors.',
          'NLJD inspection of storage cabinets and the lead designer workstation.',
          'RF spectrum analysis for low-frequency vault-penetrating transmissions.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'Indiebim found a high-resolution Wi-Fi pinhole camera and micro-audio bug integrated into a standard-looking LED spotlight in the vault ceiling.',
          'The device drew power from the lighting circuit and captured a clear overhead view of the drafting table.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Applied tamper-evident seals to lighting and security hardware.',
          'Installed ultrasonic audio jammers in the design vault.',
          'Revamped vendor-access protocol for contractors and technicians.',
        ],
      },
    ],
  },
  {
    id: 30,
    slug: 'hni-privacy-kochi-waterfront-estates',
    title: 'Ensuring HNI Privacy in Kochi’s Waterfront Estates',
    service: 'Residential TSCM, Debugging Services, and Audio Recorder Detection',
    location: 'Marine Drive / Panampilly Nagar, Kochi, Kerala',
    industry: 'High-Net-Worth Individuals (HNI) / Maritime Business Moguls',
    subjectMatterExpert:
      'Wahid Shaikh (TSCM Expert, Risk Advisor, and President of Orion Intelligence Group)',
    serviceProvider: 'Indiebim Technology Solutions Private Limited',
    summary:
      'A waterfront estate in Kochi was compromised by a weather-proof GSM transmitter concealed inside an outdoor planter with an integrated solar charger.',
    sections: [
      {
        heading: 'The Challenge',
        paragraphs: [
          'A high-profile industrialist in Kochi discovered that private legal discussions regarding family-business succession were leaking to rival factions.',
          'The client feared blackmail, loss of corporate control, and a broader compromise of personal security.',
        ],
      },
      {
        heading: 'The Problem',
        paragraphs: [
          'Luxury waterfront homes combine smart-home systems with moisture-prone conditions, which create both technical complexity and plausible excuses for repeated maintenance access.',
        ],
        bullets: [
          'Audio transmitter detection inside home automation environments.',
          'Audio recorder detection within large teak-wood interiors.',
          'Immediate need for sweeping after a major social event hosted at the villa.',
        ],
      },
      {
        heading: 'The Action',
        paragraphs: [
          'Wahid Shaikh personally supervised the Malabar Shield operation with high confidentiality across the estate’s private study, dining areas, and outdoor discussion spaces.',
        ],
        bullets: [
          'RF spectrum monitoring to isolate a hidden SSID from the master study area.',
          'Thermal imaging across automation hubs and smart televisions.',
          'Physical debugging of furniture and exterior seating zones for passive recorders.',
        ],
      },
      {
        heading: 'The Findings',
        paragraphs: [
          'The team found a long-range GSM audio transmitter with a high-gain microphone hidden inside a decorative outdoor planter on a private balcony overlooking the backwaters.',
          'The device was battery-powered and supported by a concealed solar charger built into the planter rim.',
        ],
      },
      {
        heading: 'The Solution',
        bullets: [
          'Removed the device and provided forensic analysis to legal counsel.',
          'Installed audio masking systems in the primary study and dining spaces.',
          'Enrolled the estate in a quarterly TSCM maintenance plan.',
        ],
      },
      {
        heading: 'Outcome',
        paragraphs: [
          'The client navigated the succession matter without further interference, closing the nationwide case study set with a strong residential privacy example.',
        ],
      },
    ],
  },
];

export function getCaseStudyBySlug(slug: string) {
  return caseStudies.find((study) => study.slug === slug);
}
